version: "3"

networks:
  backend-eccube:
    driver: bridge

volumes:
  mysql-database:
    driver: local

  ### ignore folder volume #####
  var:
    driver: local
  vendor:
    driver: local

services:
  ### MySQL ##################################
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - 13308:3306
    networks:
      - backend-eccube

  ### ECCube4 ##################################
  ec-cube:
    build:
      context: .
      args:
        SKIP_INSTALL_SCRIPT_ON_DOCKER_BUILD: "true"
    ports:
      - 8085:80
      - 4435:443
    volumes:
      - "./:/var/www/html:cached"
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
      - type: bind
        source: ./var/log
        target: /var/www/html/var/log
    command: /bin/sh -c "/var/www/html/dockerbuild/init-plugin.sh"
    networks:
      - backend-eccube

#### COPY FILE IN CONTAINER TO HOST - RUN COMMAND WITH ADMINISTRATOR
#docker cp ec-cube-dev-test_ec-cube_1:/var/www/html/vendor ./